import Foundation

/// Events emitted by a provider during streaming. Both OpenAI and Anthropic map to this unified set.
public enum ChatStreamEvent: Sendable, Equatable {
    /// A text delta to append to the current assistant message.
    case text(String)
    /// A reasoning/thinking delta (streamed before the answer).
    case reasoning(String)
    /// A complete Anthropic thinking block — text + signature for round-tripping.
    case thinkingBlockComplete(thinking: String, signature: String)
    /// An Anthropic redacted thinking block (encrypted, must be preserved verbatim).
    case redactedThinking(data: String)
    /// A complete tool call ready for execution.
    case toolCallComplete(id: String, name: String, arguments: String)
    /// Token usage statistics (typically in the final chunk).
    case usage(TokenUsage)
    /// Stream finished normally.
    case done
}

public struct TokenUsage: Sendable, Equatable {
    /// Tokens consumed by prompt and conversation history.
    public let promptTokens: Int
    /// Tokens generated by the model for the completion.
    public let completionTokens: Int
    /// Total tokens billed for the request.
    public let totalTokens: Int

    /// Creates a normalized usage payload emitted during or after streaming.
    ///
    /// - Parameters:
    ///   - promptTokens: Tokens used by input context.
    ///   - completionTokens: Tokens generated by the assistant.
    ///   - totalTokens: Combined prompt and completion token count.
    public init(promptTokens: Int, completionTokens: Int, totalTokens: Int) {
        self.promptTokens = promptTokens
        self.completionTokens = completionTokens
        self.totalTokens = totalTokens
    }
}
